---

- name: ensure the official Node.js package repository is configured
  apt_repository: repo='ppa:chris-lea/node.js'

- name: ensure required packages are present
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - nodejs

- name: ensure global Node.js packages are present
  npm: name={{ item }} global=yes
  with_items:
    - sails
