---

- name: ensure common packages are present
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - python-software-properties
    - vim

- name: ensure that vim is the default editor
  command: update-alternatives --set editor /usr/bin/vim.basic

- name: ensure the bashrc file is present
  copy: src=bashrc dest=/home/{{ ansible_env.SUDO_USER }}/.bashrc mode=0700

- name: Dump all variables
  connection: local
  local_action: template src=environment.j2 dest={{ inventory_dir }}/environment.log
  sudo: no
